{
 "title": "PSB Dashboard",
 "time": { "from": "2023-01-01T00:00:00.000Z", "to": "2024-12-01T00:00:00.000Z" },
 "templating": {
  "list": [
   {
    "name": "metric",
    "label": "Metric",
    "query": "SELECT DISTINCT metric FROM metrics_data"
   },
   {
    "name": "metric_type",
    "label": "Metric type",
    "query": "SELECT DISTINCT metric_type FROM metrics_data ORDER BY metric_type"
   },
   {
    "name": "year",
    "query": "SELECT DISTINCT year FROM metrics_data ORDER BY year"
   }
  ]
 },
 "panels": [
  { "title": "Производные метрики", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Коэфициент вариации реальных показателей",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "dataset": "neondb",
     "rawSql": "SELECT \n    md.metric,\n    STDDEV(md.value)/AVG(md.value) as coeficient\nFROM metrics_data md\nWHERE md.metric_type = 'Факт'\nGROUP BY md.metric"
    }
   ]
  },
  {
   "title": "Выполнение плана ФОТ",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "neondb",
     "rawSql": "SELECT \n    AVG(CASE WHEN md.metric_type = 'Факт' THEN md.value END) / \n    AVG(CASE WHEN md.metric_type = 'План' THEN md.value END) * 100 as plan_completion\nFROM metrics_data md\nWHERE md.metric = 'ФОТ' \n  AND md.year = ${year}"
    }
   ]
  },
  {
   "title": "Выполнение плана Текучесть",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "neondb",
     "rawSql": "SELECT \n    AVG(CASE WHEN md.metric_type = 'Факт' THEN md.value END) / \n    AVG(CASE WHEN md.metric_type = 'План' THEN md.value END) * 100 as plan_completion\nFROM metrics_data md\nWHERE md.metric = 'Текучесть' \n  AND md.year = ${year}"
    }
   ]
  },
  {
   "title": "Выполнение плана по налогам",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "neondb",
     "rawSql": "SELECT \n    AVG(CASE WHEN md.metric_type = 'Факт' THEN md.value END) / \n    AVG(CASE WHEN md.metric_type = 'План' THEN md.value END) * 100 as plan_completion\nFROM metrics_data md\nWHERE md.metric = 'Налог' \n  AND md.year = ${year}"
    }
   ]
  },
  {
   "title": "Выполнение плана Численности",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "neondb",
     "rawSql": "SELECT \n    AVG(CASE WHEN md.metric_type = 'Факт' THEN md.value END) / \n    AVG(CASE WHEN md.metric_type = 'План' THEN md.value END) * 100 as plan_completion\nFROM metrics_data md\nWHERE md.metric = 'Численность' \n  AND md.year = ${year}"
    }
   ]
  },
  { "title": "Анализ метрик в динамике", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Фактиечская и плановая динамика метрики",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "dataset": "neondb",
     "rawSql": "SELECT \n    TO_DATE(CONCAT(md.year, '-', md.month, '-01'), 'YYYY-MM-DD') as time,\n    md.metric,\n    ml.month_name,\n    MAX(CASE WHEN md.metric_type = 'Факт' THEN md.value END) as fact,\n    MAX(CASE WHEN md.metric_type = 'План' THEN md.value END) as plan\nFROM metrics_data md\nJOIN months_lookup ml ON md.month = ml.month\nJOIN metrics_metadata mm ON md.metric = mm.metric AND md.year = mm.period\nWHERE \n    md.metric = '${metric}'\n    AND md.metric_type IN ('Факт', 'План')\nGROUP BY time, md.metric, ml.month_name\nORDER BY time;"
    }
   ]
  },
  {
   "title": "Вид и тип метрики",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "dataset": "neondb",
     "rawSql": "SELECT \n    TO_DATE(CONCAT(md.year, '-', md.month, '-01'), 'YYYY-MM-DD') as time,\n    md.value,\n    mm.market\nFROM metrics_data md\nJOIN months_lookup ml ON md.month = ml.month\nJOIN metrics_metadata mm ON md.metric = mm.metric AND md.year = mm.period\nWHERE \n    md.metric = '${metric}'\n    AND md.metric_type = '${metric_type}'\nORDER BY time;"
    }
   ]
  },
  { "title": "Рыночные метрики", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Численность",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 38 },
   "targets": [
    {
     "dataset": "neondb",
     "rawSql": "SELECT metric, market\nFROM metrics_metadata as mm\nWHERE metric = 'Численность'\nAND period = ${year}"
    }
   ]
  },
  {
   "title": "Налог",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 38 },
   "targets": [
    {
     "dataset": "neondb",
     "rawSql": "SELECT metric, market\nFROM metrics_metadata as mm\nWHERE metric = 'Налог'\nAND period = ${year}"
    }
   ]
  },
  {
   "title": "ФОТ",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 38 },
   "targets": [
    {
     "dataset": "neondb",
     "rawSql": "SELECT metric, market\nFROM metrics_metadata as mm\nWHERE metric = 'ФОТ'\nAND period = ${year}"
    }
   ]
  },
  {
   "title": "Текучесть",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 38 },
   "targets": [
    {
     "dataset": "neondb",
     "rawSql": "SELECT metric, market\nFROM metrics_metadata as mm\nWHERE metric = 'Текучесть'\nAND period = ${year}"
    }
   ]
  },
  { "title": "Раздельный анализ метрик", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "График текучести",
   "type": "timeseries",
   "description": "Показывает график изменения метрики текучести",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {
     "dataset": "neondb",
     "rawSql": "SELECT \n    TO_DATE(CONCAT(md.year, '-', md.month, '-01'), 'YYYY-MM-DD') as time,\n    md.metric,\n    ml.month_name,\n    MAX(CASE WHEN md.metric_type = 'Факт' THEN md.value END) as fact,\n    MAX(CASE WHEN md.metric_type = 'План' THEN md.value END) as plan\nFROM metrics_data md\nJOIN months_lookup ml ON md.month = ml.month\nJOIN metrics_metadata mm ON md.metric = mm.metric AND md.year = mm.period\nWHERE \n    md.metric = 'Текучесть'\n    AND md.metric_type IN ('Факт', 'План')\nGROUP BY time, md.metric, ml.month_name\nORDER BY time;"
    }
   ]
  },
  {
   "title": "График ФОТ",
   "type": "timeseries",
   "description": "Показывает график изменения метрики ФОТ",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 55 },
   "targets": [
    {
     "dataset": "neondb",
     "rawSql": "SELECT \n    TO_DATE(CONCAT(md.year, '-', md.month, '-01'), 'YYYY-MM-DD') as time,\n    md.metric,\n    ml.month_name,\n    MAX(CASE WHEN md.metric_type = 'Факт' THEN md.value END) as fact,\n    MAX(CASE WHEN md.metric_type = 'План' THEN md.value END) as plan\nFROM metrics_data md\nJOIN months_lookup ml ON md.month = ml.month\nJOIN metrics_metadata mm ON md.metric = mm.metric AND md.year = mm.period\nWHERE \n    md.metric = 'ФОТ'\n    AND md.metric_type IN ('Факт', 'План')\nGROUP BY time, md.metric, ml.month_name\nORDER BY time;"
    }
   ]
  },
  {
   "title": "График налогов",
   "type": "timeseries",
   "description": "Показывает график изменения метрики налога",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 65 },
   "targets": [
    {
     "dataset": "neondb",
     "rawSql": "SELECT \n    TO_DATE(CONCAT(md.year, '-', md.month, '-01'), 'YYYY-MM-DD') as time,\n    md.metric,\n    ml.month_name,\n    MAX(CASE WHEN md.metric_type = 'Факт' THEN md.value END) as fact,\n    MAX(CASE WHEN md.metric_type = 'План' THEN md.value END) as plan\nFROM metrics_data md\nJOIN months_lookup ml ON md.month = ml.month\nJOIN metrics_metadata mm ON md.metric = mm.metric AND md.year = mm.period\nWHERE \n    md.metric = 'Налог'\n    AND md.metric_type IN ('Факт', 'План')\nGROUP BY time, md.metric, ml.month_name\nORDER BY time;"
    }
   ]
  },
  {
   "title": "График текучести",
   "type": "barchart",
   "description": "Показывает график изменения метрики текучести",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 75 },
   "targets": [
    {
     "dataset": "neondb",
     "rawSql": "SELECT \n    TO_DATE(CONCAT(md.year, '-', md.month, '-01'), 'YYYY-MM-DD') as time,\n    md.metric,\n    ml.month_name,\n    MAX(CASE WHEN md.metric_type = 'Факт' THEN md.value END) as fact,\n    MAX(CASE WHEN md.metric_type = 'План' THEN md.value END) as plan\nFROM metrics_data md\nJOIN months_lookup ml ON md.month = ml.month\nJOIN metrics_metadata mm ON md.metric = mm.metric AND md.year = mm.period\nWHERE \n    md.metric = 'Численность'\n    AND md.metric_type IN ('Факт', 'План')\nGROUP BY time, md.metric, ml.month_name\nORDER BY time;"
    }
   ]
  }
 ]
}